# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_filename', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=64)),
                ('extra_type', models.CharField(max_length=32)),
                ('extension', models.CharField(max_length=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('store', models.PositiveSmallIntegerField()),
                ('filename', models.CharField(max_length=16, unique=True)),
                ('extension', models.CharField(max_length=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=False)),
                ('board', models.PositiveSmallIntegerField()),
                ('source', models.TextField()),
                ('size', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='extra',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
        migrations.AddField(
            model_name='extra',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
