# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('when', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
