# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadID', models.CharField(max_length=32)),
                ('filename', models.CharField(blank=True, max_length=256)),
                ('tempname', models.CharField(max_length=256)),
                ('store', models.PositiveSmallIntegerField()),
                ('extension', models.CharField(blank=True, max_length=6)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('activeTime', models.DateTimeField()),
                ('expectedChunk', models.PositiveSmallIntegerField(default=0)),
                ('private', models.BooleanField(default=False)),
                ('board', models.PositiveSmallIntegerField()),
                ('url', models.URLField(max_length=1024)),
                ('title', models.CharField(max_length=256)),
                ('downloadType', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(max_length=16)),
                ('filesize', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
