# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_upload_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='options',
            field=models.CharField(blank=True, max_length=32768, null=True),
        ),
    ]
