# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20170829_1210'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='posttag',
            index=models.Index(fields=['post', 'tag'], name='tags_postta_post_id_5ad922_idx'),
        ),
    ]
