# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20170829_1227'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tagchance',
            name='tags_tagcha_parent__e1054c_idx',
        ),
        migrations.RemoveIndex(
            model_name='tagchance',
            name='tags_tagcha_child_i_f15b7d_idx',
        ),
    ]
