# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20170902_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagchance',
            name='child',
        ),
        migrations.RemoveField(
            model_name='tagchance',
            name='parent',
        ),
        migrations.DeleteModel(
            name='TagChance',
        ),
    ]
