# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-28 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_options'),
        ('tags', '0006_auto_20180527_1652'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagdeclination',
            unique_together=set([('post', 'tag')]),
        ),
    ]
